name: Building Praat!

on:
  push:
  pull_request:
  workflow_call:

jobs:
  BuildLinux:
    strategy:
      matrix:
        include:
          - version: clang
            targetos: linux
            ccache_path: sccache
            toolchain: ""
            prefix: ""
            makefile: makefile.defs.linux.pulse-clang
            binary: praat
            extension: ""
    name: "Build: ${{ matrix.targetos }} ${{ matrix.version }}"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.targetos }}-${{ matrix.version }}-ccache
          variant: sccache

      - name: Install dependencies
        run: sudo apt-get install -y libgtk-3-dev libasound2-dev libpulse-dev libjack-dev binutils-mingw-w64

      - name: Download and Install LLVM-Mingw toolchain (only for Windows)
        if: matrix.targetos == 'windows'
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/nightly/${{ matrix.toolchain }}.tar.xz
          tar -xvf ${{ matrix.toolchain }}.tar.xz

      - name: Build Praat (${{ matrix.targetos }})
        run: |
          cp makefiles/${{ matrix.makefile }} makefile.defs

          # Define PREFIX with PWD and toolchain path for Windows
          if [ "${{ matrix.toolchain }}" != "" ]; then
            PREFIX="$(pwd)/${{ matrix.toolchain }}/bin/${{ matrix.prefix }}"
          else
            PREFIX="${{ matrix.prefix }}"
          fi

          # Unify the make command, only CC and CXX change
          make -j$(nproc) \
            PREFIX="${PREFIX}" \
            CC="${{ matrix.ccache_path }} ${PREFIX}clang" \
            CXX="${{ matrix.ccache_path }} ${PREFIX}clang++"

          # Copy binary output with platform and version specific naming
          cp ${{ matrix.binary }} Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

      - name: Upload binary (Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }})
        uses: actions/upload-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}
          path: Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

  BuildWindows:
    strategy:
      matrix:
        include:
          - version: aarch64
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: aarch64-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
          - version: x86_64
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: x86_64-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
          - version: intel32
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: i686-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
    name: "Build: ${{ matrix.targetos }} ${{ matrix.version }}"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.targetos }}-${{ matrix.version }}-ccache
          variant: sccache

      - name: Install dependencies
        run: sudo apt-get install -y libgtk-3-dev libasound2-dev libpulse-dev libjack-dev binutils-mingw-w64

      - name: Download and Install LLVM-Mingw toolchain (only for Windows)
        if: matrix.targetos == 'windows'
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/nightly/${{ matrix.toolchain }}.tar.xz
          tar -xvf ${{ matrix.toolchain }}.tar.xz

      - name: Build Praat (${{ matrix.targetos }})
        run: |
          cp makefiles/${{ matrix.makefile }} makefile.defs

          # Define PREFIX with PWD and toolchain path for Windows
          if [ "${{ matrix.toolchain }}" != "" ]; then
            PREFIX="$(pwd)/${{ matrix.toolchain }}/bin/${{ matrix.prefix }}"
          else
            PREFIX="${{ matrix.prefix }}"
          fi

          # Unify the make command, only CC and CXX change
          make -j$(nproc) \
            PREFIX="${PREFIX}" \
            CC="${{ matrix.ccache_path }} ${PREFIX}clang" \
            CXX="${{ matrix.ccache_path }} ${PREFIX}clang++"

          # Copy binary output with platform and version specific naming
          cp ${{ matrix.binary }} Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

      - name: Upload binary (Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }})
        uses: actions/upload-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}
          path: Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

  BuildMacOS:
    name: "Build: ${{ matrix.targetos }} ${{ matrix.version }}"
    strategy:
      matrix:
        include:
          - runner: macos-13
            targetos: "macOS13"
            version: Ventura
            extension: .dmg
          - runner: macos-15
            targetos: "macOS15"
            version: Sequoia-arm64
            extension: .dmg
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract praat xcodeproj
        run: |
          curl -LO https://github.com/praat/praat/releases/download/v6.4.30/praat6430_xcodeproj.zip
          unzip praat6430_xcodeproj.zip -d .

      - name: Fix wrong portaudio path
        run: |
          sed -i '' 's|../../../support/external/portaudio/portaudio 20210406/src/common/||g' praat.xcodeproj/project.pbxproj

      - name: Set up Xcode version
        run: |
          if [[ "${{ matrix.runner }}" == "macos-13" ]]; then
            sudo xcode-select -s /Applications/Xcode_15.2.app
          elif [[ "${{ matrix.runner }}" == "macos-15" ]]; then
            sudo xcode-select -s /Applications/Xcode_16.3.app
          fi

      - name: Build Praat with xcodebuild
        run: |
          xcodebuild \
            -project praat.xcodeproj \
            -scheme praat_mac \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SYMROOT=build

      - name: Create DMG with Praat app
        run: |
          hdiutil create -fs HFS+ -ov -srcfolder build/Configuration64/Praat.app -volname Praat_${{ matrix.runner }}_${{ matrix.version }} praat_app.dmg
          hdiutil convert -ov -format UDZO -o Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} praat_app.dmg

      - name: Upload binary (Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }})
        uses: actions/upload-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}
          path: Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

  TestLinux:
    name: "Test: Linux"
    runs-on: ubuntu-22.04
    needs: BuildLinux
    strategy:
      matrix:
        version: [clang]
        targetos: [linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}

      - name: Install dependencies
        run: sudo apt-get install -y libgtk-3-0 libasound2 libpulse0 libjack0

      - name: Apply executable permission
        run: chmod +x ./Praat-${{ matrix.targetos }}_${{ matrix.version }}

      - name: Run Praat tests
        run: ./Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} --run test/runAllTests_batch.praat

      - name: Run Praat dwtests
        run: ./Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} --run dwtest/runAllTests_batch.praat

  TestWindows:
    name: "Test: Windows"
    needs: BuildWindows
    strategy:
      matrix:
        include:
          - version: aarch64
            targetos: windows
            runner: windows-11-arm
            extension: .exe
          - version: x86_64
            targetos: windows
            runner: windows-latest
            extension: .exe
          - version: intel32
            targetos: windows
            runner: windows-latest
            extension: .exe
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}

      - name: Run Praat tests
        shell: cmd
        run: |
          .\Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} --run test/runAllTests_batch.praat

      - name: Run Praat dwtests
        shell: cmd
        run: |
          .\Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} --run dwtest/runAllTests_batch.praat

  TestMacOS:
    name: "Test: macOS"
    needs: BuildMacOS
    strategy:
      matrix:
        include:
          - runner: macos-13
            targetos: "macOS13"
            version: Ventura
            extension: .dmg
          - runner: macos-15
            targetos: "macOS15"
            version: Sequoia-arm64
            extension: .dmg
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}

      - name: Apply executable permission
        run: |
          hdiutil attach Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} -mountpoint /Volumes/Praat
          cp "/Volumes/Praat/Praat.app/Contents/MacOS/Praat" praat
          chmod +x praat

      - name: Run Praat tests
        run: ./praat --run test/runAllTests_batch.praat

      - name: Run Praat dwtests
        run: ./praat --run dwtest/runAllTests_batch.praat

      - name: Unmount DMG
        if: always()
        run: hdiutil detach /Volumes/Praat
