name: Building Praat!

on:
  push:
  pull_request:
  workflow_call:

jobs:
  Build:
    strategy:
      matrix:
        include:
          - version: aarch64
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: aarch64-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
          - version: x86_64
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: x86_64-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
          - version: intel32
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: i686-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
          - version: clang
            targetos: linux
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: ""
            makefile: makefile.defs.linux.pulse-clang
            binary: praat
            extension: ""

    name: Praat (${{ matrix.version }}) (${{ matrix.binary }})
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ runner.os }}-${{ matrix.version }}-ccache
          variant: sccache

      - name: Install dependencies
        run: sudo apt install -y make rsync pkg-config libgtk-3-dev libasound2-dev libpulse-dev libjack-dev clang gcc g++ binutils binutils-mingw-w64 xvfb wget

      - name: Download and Install LLVM-Mingw toolchain
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/nightly/${{ matrix.toolchain }}.tar.xz
          tar -xvf ${{ matrix.toolchain }}.tar.xz

      - name: Build Praat
        run: |
          cp makefiles/${{ matrix.makefile }} makefile.defs
          make -j$(nproc) \
            PREFIX="$(pwd)/${{ matrix.toolchain }}/bin/${{ matrix.prefix }}" \
            CC="${{ matrix.ccache_path }} $(pwd)/${{ matrix.toolchain }}/bin/${{ matrix.prefix }}clang" \
            CXX="${{ matrix.ccache_path }} $(pwd)/${{ matrix.toolchain }}/bin/${{ matrix.prefix }}clang++"
          cp ${{ matrix.binary }} Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Praat for ${{ matrix.targetos }} ${{ matrix.version }}
          path: Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}
