name: Building Praat!

on:
  push:
  pull_request:
  workflow_call:

jobs:
  BuildLinux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: clang
            targetos: linux
            ccache_path: sccache
            toolchain: ""
            prefix: ""
            makefile: makefile.defs.linux.pulse-clang
            binary: praat
            extension: ""
            continue: false
          - version: arm32
            targetos: linux
            ccache_path: sccache
            toolchain: ""
            prefix: arm-linux-gnueabihf-
            makefile: makefile.defs.linux.rpi
            binary: praat
            extension: ""
            continue: true
          - version: arm64
            targetos: linux
            ccache_path: sccache
            toolchain: ""
            prefix: aarch64-linux-gnu-
            makefile: makefile.defs.linux.rpi
            binary: praat
            extension: ""
            continue: true
          - version: s390x
            targetos: linux
            ccache_path: sccache
            toolchain: ""
            prefix: ""
            makefile: makefile.defs.linux.s390x.pulse
            binary: praat
            extension: ""
            continue: true

    name: Praat (${{ matrix.targetos }}) (${{ matrix.version }})
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.targetos }}-${{ matrix.version }}-ccache
          variant: sccache

      - name: Install dependencies
        run: sudo apt install -y libgtk-3-dev libasound2-dev libpulse-dev libjack-dev binutils-mingw-w64 clang-12 aarch64-linux-gnu-clang arm-linux-gnueabihf-clang

      - name: Download and Install LLVM-Mingw toolchain (only for Windows)
        if: matrix.targetos == 'windows'
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/nightly/${{ matrix.toolchain }}.tar.xz
          tar -xvf ${{ matrix.toolchain }}.tar.xz

      - name: Build Praat (${{ matrix.targetos }})
        continue-on-error: ${{ matrix.continue }}
        run: |
          cp makefiles/${{ matrix.makefile }} makefile.defs

          # Define PREFIX with PWD and toolchain path for Windows
          if [ "${{ matrix.toolchain }}" != "" ]; then
            PREFIX="$(pwd)/${{ matrix.toolchain }}/bin/${{ matrix.prefix }}"
          else
            PREFIX="${{ matrix.prefix }}"
          fi

          # Unify the make command, only CC and CXX change
          make -j$(nproc) \
            PREFIX="${PREFIX}" \
            CC="${{ matrix.ccache_path }} ${PREFIX}clang" \
            CXX="${{ matrix.ccache_path }} ${PREFIX}clang++"

          # Copy binary output with platform and version specific naming
          cp ${{ matrix.binary }} Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

      - name: Upload binary (Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }})
        uses: actions/upload-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}
          path: Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

  BuildChrome64:
    name: Praat (chrome64)
    runs-on: ubuntu-22.04
    container:
      image: selenium/standalone-chrome:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build for ChromeOS 64-bit (chrome64)
        continue-on-error: true
        run: |
          cp makefiles/makefile.defs.linux.chrome64 makefile.defs
          make -j$(nproc) CC=clang CXX=clang++
          cp praat Praat-linux_chrome64

      - name: Upload binary (Praat-linux_chrome64)
        uses: actions/upload-artifact@v4
        with:
          name: Praat-linux_chrome64
          path: Praat-linux_chrome64

  BuildWindows:
    strategy:
      matrix:
        include:
          - version: aarch64
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: aarch64-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
          - version: x86_64
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: x86_64-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe
          - version: intel32
            targetos: windows
            ccache_path: sccache
            toolchain: llvm-mingw-nightly-ucrt-ubuntu-22.04-x86_64
            prefix: i686-w64-mingw32-
            makefile: makefile.defs.msys-clang
            binary: Praat.exe
            extension: .exe

    name: Praat (${{ matrix.targetos }}) (${{ matrix.version }})
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.targetos }}-${{ matrix.version }}-ccache
          variant: sccache

      - name: Install dependencies
        run: sudo apt install -y libgtk-3-dev libasound2-dev libpulse-dev libjack-dev binutils-mingw-w64

      - name: Download and Install LLVM-Mingw toolchain (only for Windows)
        if: matrix.targetos == 'windows'
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/nightly/${{ matrix.toolchain }}.tar.xz
          tar -xvf ${{ matrix.toolchain }}.tar.xz

      - name: Build Praat (${{ matrix.targetos }})
        run: |
          cp makefiles/${{ matrix.makefile }} makefile.defs

          # Define PREFIX with PWD and toolchain path for Windows
          if [ "${{ matrix.toolchain }}" != "" ]; then
            PREFIX="$(pwd)/${{ matrix.toolchain }}/bin/${{ matrix.prefix }}"
          else
            PREFIX="${{ matrix.prefix }}"
          fi

          # Unify the make command, only CC and CXX change
          make -j$(nproc) \
            PREFIX="${PREFIX}" \
            CC="${{ matrix.ccache_path }} ${PREFIX}clang" \
            CXX="${{ matrix.ccache_path }} ${PREFIX}clang++"

          # Copy binary output with platform and version specific naming
          cp ${{ matrix.binary }} Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

      - name: Upload binary (Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }})
        uses: actions/upload-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}
          path: Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }}

  TestLinux:
    name: Run Linux tests
    runs-on: ubuntu-22.04
    needs: BuildLinux
    strategy:
      matrix:
        version: [clang]
        targetos: [linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-0 libasound2 libpulse0 libjack0

      - name: Run Praat tests
        run: |
          chmod +x ./Praat-${{ matrix.targetos }}_${{ matrix.version }}
          ./Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} -a --run test/runAllTests_batch.praat
          ./Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} -a --run dwtest/runAllTests_batch.praat

  TestWindows:
    name: Run Windows tests
    needs: BuildWindows
    strategy:
      matrix:
        include:
          - version: aarch64
            targetos: windows
            runner: windows-11-arm
            extension: .exe
          - version: x86_64
            targetos: windows
            runner: windows-latest
            extension: .exe
          - version: intel32
            targetos: windows
            runner: windows-latest
            extension: .exe

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-${{ matrix.targetos }}_${{ matrix.version }}

      - name: Run Praat tests
        shell: cmd
        run: |
          .\Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} -a --run test/runAllTests_batch.praat
          .\Praat-${{ matrix.targetos }}_${{ matrix.version }}${{ matrix.extension }} -a --run dwtest/runAllTests_batch.praat

  TestChrome64:
    name: Run Chrome64 tests
    needs: BuildChrome64
    runs-on: ubuntu-22.04
    container:
      image: selenium/standalone-chrome:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-linux_chrome64

      - name: Run Chrome64-specific tests
        continue-on-error: true
        run: |
          chmod +x ./Praat-linux_chrome64
          ./Praat-linux_chrome64 -a --run test/runAllTests_batch.praat
          ./Praat-linux_chrome64 -a --run dwtest/runAllTests_batch.praat

  TestS390x:
    name: Run s390x tests
    needs: BuildLinux
    runs-on: ubuntu-22.04
    container:
      image: multiarch/qemu-user-static:s390x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-linux_s390x

      - name: Run s390x-specific tests
        continue-on-error: true
        run: |
          chmod +x ./Praat-linux_s390x
          ./Praat-linux_s390x -a --run test/runAllTests_batch.praat
          ./Praat-linux_s390x -a --run dwtest/runAllTests_batch.praat

  TestRpi:
    name: Run Raspberry Pi tests
    needs: BuildLinux
    strategy:
      matrix:
        include:
          - version: arm64
            arch: rpi64
          - version: arm32
            arch: rpi32
    runs-on: ubuntu-22.04
    container:
      image: arm64v8/debian:bullseye-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Praat-linux_${{ matrix.version }}

      - name: Run Raspberry Pi-specific tests
        continue-on-error: true
        run: |
          chmod +x ./Praat-linux_${{ matrix.version }}
          ./Praat-linux_${{ matrix.version }} -a --run test/runAllTests_batch.praat
          ./Praat-linux_${{ matrix.version }} -a --run dwtest/runAllTests_batch.praat
