name: Build and Test Praat

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  Build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            compiler: clang
            makefile: makefiles/makefile.defs.linux.pulse-clang
            binary: praat
          - os: ubuntu-24.04
            compiler: gcc
            makefile: makefiles/makefile.defs.linux.pulse-gcc
            binary: praat
          - os: ubuntu-24.04
            arch: mingw64
            makefile: makefiles/makefile.defs.msys-mingw64
            binary: Praat.exe
          - os: ubuntu-24.04
            arch: mingw32
            makefile: makefiles/makefile.defs.msys-mingw32
            binary: Praat.exe

    name: Build ${{ matrix.os }} ${{ matrix.compiler || matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make rsync pkg-config \
              libgtk-3-dev libasound2-dev libpulse-dev libjack-dev \
              clang gcc g++ mingw-w64 ccache

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ matrix.compiler || matrix.arch }}-ccache

      - name: Configure ccache and Toolchain
        run: |
          ccache --max-size=5G
          if [[ "${{ matrix.arch }}" == "mingw64" ]]; then
            export PATH="/usr/x86_64-w64-mingw32/bin:$PATH"
          elif [[ "${{ matrix.arch }}" == "mingw32" ]]; then
            export PATH="/usr/i686-w64-mingw32/bin:$PATH"
          fi

      - name: Build Praat
        run: |
          cp ${{ matrix.makefile }} makefile.defs
          if [[ "${{ matrix.arch }}" == "mingw64" ]]; then
            ccache make -j$(nproc) CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
          elif [[ "${{ matrix.arch }}" == "mingw32" ]]; then
            ccache make -j$(nproc) CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
          else
            ccache make -j$(nproc)
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: praat-${{ matrix.arch || matrix.compiler }}
          path: ${{ matrix.binary }}
