name: Release Praat

on:
  push:
    branches:
      - master
    paths:
      - praat
      - praat_barren
      - praat.exe
      - CHANGELOG.md
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/build-praat.yml
    secrets: inherit

  release:
    name: 🚀 Publish Release
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🏮 Checkout
        uses: actions/checkout@v4

      - name: 🗅 Get current date
        id: date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: 📤 Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 📥 Upload binaries to release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: |
            artifacts/praat-linux-clang.tar.gz
            artifacts/praat-linux-gcc.tar.gz
            artifacts/praat-windows-intel64.zip
            artifacts/praat-windows-intel32.zip
          allowUpdates: true
          replacesArtifacts: true
          tag: latest
          name: "Praat Release ${{ steps.date.outputs.NOW }}"
          bodyFile: CHANGELOG.md
